import type { Metadata } from "next";
import PrimarySearchAppBar from "~/common/components/shared/header";
import Sidebar from "~/common/components/shared/sidebar";
import { NextUIProvider } from "@nextui-org/react";

export const metadata: Metadata = {
  title: "لوحة التحكم",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }: { children: React.ReactNode }) {

  return (
      <div className={`flex flex-row`}>
        <div className="w-full xs:w-[400px] flex-1  " >
          <div className="flex-1 sticky z-[999] bg-[#F7F7F7]  top-0">
            <PrimarySearchAppBar iconToggle />
          </div>
          <section className=" bg-[#F7F7F7] min-h-screen " >
            <NextUIProvider>
              {children}
            </NextUIProvider>
          </section>
        </div>
        <Sidebar />
      </div>
  );
}
